### ISSUE TITLE
Errors react dapp with ethers

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web-examples#98]
I'm trying to run the react-dapp-v2-with-ethers on localhost, I added the project ID to the env file, I ran yarn to install dependencies, but when I run it on localhost there's  no connect button and I get this errors:

```hot-dev-client.js?1600:85 ./src/pages/index.tsx
Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)
printWarnings @ hot-dev-client.js?1600:85
next-dev.js?3515:20 Warning: Prop `className` did not match. Server: "sc-cwSeag kMFonq" Client: "sc-cwSeag dPQxxS"
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at Toggle (webpack-internal:///./src/components/Toggle.tsx:46:22)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at Column (webpack-internal:///./src/components/Column.tsx:44:26)
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at Column (webpack-internal:///./src/components/Column.tsx:44:26)
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at Wrapper (webpack-internal:///./src/components/Wrapper.tsx:47:26)
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at Column (webpack-internal:///./src/components/Column.tsx:44:26)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at Home (webpack-internal:///./src/pages/index.tsx:54:62)
    at ClientContextProvider (webpack-internal:///./src/contexts/ClientContext.tsx:42:26)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:30:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20740)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23547)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:70:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:569:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:691:27) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
window.console.error @ next-dev.js?3515:20
ws.js?dc4f:93 WebSocket connection to 'wss://relay.walletconnect.com/?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtrWmVzSmRwUVBjQXVHeGVEZGU4VzZTMkFldmIzUEhYdnpXZWN2NFhYc2dTWSIsInN1YiI6IjFmYjU1OWVlZWExYTEzZTZjZjYwOTU0MzU5NWE3NzY4ZTBjOTEzNTI0MjIxOWZiNmE3NGM0MTc0Mzg1MmYzNjYiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3MjA0MTQ4MywiZXhwIjoxNjcyMTI3ODgzfQ.zlEsFeXNF31S_3xL7ergLWW_x2VZ6xW2vE2fhzwZM-VrgUCEy0ME0r3SFqkZZpNNEGQrCEipfNccRJ_nFB6uAg&ua=wc-2%2Fjs-2.1.3%2Fwindows10-chrome-108.0.0%2Fbrowser%3Alocalhost%3A3000' failed: 
eval @ ws.js?dc4f:93
browser.js?3aea:202 Object 'Core Initilization Failure at epoch 1672041484240' Error: WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtrWmVzSmRwUVBjQXVHeGVEZGU4VzZTMkFldmIzUEhYdnpXZWN2NFhYc2dTWSIsInN1YiI6IjFmYjU1OWVlZWExYTEzZTZjZjYwOTU0MzU5NWE3NzY4ZTBjOTEzNTI0MjIxOWZiNmE3NGM0MTc0Mzg1MmYzNjYiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3MjA0MTQ4MywiZXhwIjoxNjcyMTI3ODgzfQ.zlEsFeXNF31S_3xL7ergLWW_x2VZ6xW2vE2fhzwZM-VrgUCEy0ME0r3SFqkZZpNNEGQrCEipfNccRJ_nFB6uAg&ua=wc-2%2Fjs-2.1.3%2Fwindows10-chrome-108.0.0%2Fbrowser%3Alocalhost%3A3000
    at ft.transportOpen (index.es.js?e35d:1:32288)
    at async Promise.all (:3000/index 1)
    at async ft.init (index.es.js?e35d:1:30881)
    at async V.initialize (index.es.js?e35d:1:52200)
    at async V.start (index.es.js?e35d:1:52102)
    at async C.initialize (index.es.js?eb21:1:25044)
    at async C.init (index.es.js?eb21:1:24873)
    at async a.createClient (index.es.js?380e:1:6082)
    at async a.initialize (index.es.js?380e:1:5952)
    at async a.init (index.es.js?380e:1:4330)
LOG @ browser.js?3aea:202
next-dev.js?3515:20 Object 'WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtrWmVzSmRwUVBjQXVHeGVEZGU4VzZTMkFldmIzUEhYdnpXZWN2NFhYc2dTWSIsInN1YiI6IjFmYjU1OWVlZWExYTEzZTZjZjYwOTU0MzU5NWE3NzY4ZTBjOTEzNTI0MjIxOWZiNmE3NGM0MTc0Mzg1MmYzNjYiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3MjA0MTQ4MywiZXhwIjoxNjcyMTI3ODgzfQ.zlEsFeXNF31S_3xL7ergLWW_x2VZ6xW2vE2fhzwZM-VrgUCEy0ME0r3SFqkZZpNNEGQrCEipfNccRJ_nFB6uAg&ua=wc-2%2Fjs-2.1.3%2Fwindows10-chrome-108.0.0%2Fbrowser%3Alocalhost%3A3000'
window.console.error @ next-dev.js?3515:20
browser.js?3aea:202 Object 'SignClient Initilization Failure'
next-dev.js?3515:20 Object 'WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtrWmVzSmRwUVBjQXVHeGVEZGU4VzZTMkFldmIzUEhYdnpXZWN2NFhYc2dTWSIsInN1YiI6IjFmYjU1OWVlZWExYTEzZTZjZjYwOTU0MzU5NWE3NzY4ZTBjOTEzNTI0MjIxOWZiNmE3NGM0MTc0Mzg1MmYzNjYiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3MjA0MTQ4MywiZXhwIjoxNjcyMTI3ODgzfQ.zlEsFeXNF31S_3xL7ergLWW_x2VZ6xW2vE2fhzwZM-VrgUCEy0ME0r3SFqkZZpNNEGQrCEipfNccRJ_nFB6uAg&ua=wc-2%2Fjs-2.1.3%2Fwindows10-chrome-108.0.0%2Fbrowser%3Alocalhost%3A3000'
window.console.error @ next-dev.js?3515:20
index.es.js?e35d:1 Uncaught (in promise) Error: WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtrWmVzSmRwUVBjQXVHeGVEZGU4VzZTMkFldmIzUEhYdnpXZWN2NFhYc2dTWSIsInN1YiI6IjFmYjU1OWVlZWExYTEzZTZjZjYwOTU0MzU5NWE3NzY4ZTBjOTEzNTI0MjIxOWZiNmE3NGM0MTc0Mzg1MmYzNjYiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3MjA0MTQ4MywiZXhwIjoxNjcyMTI3ODgzfQ.zlEsFeXNF31S_3xL7ergLWW_x2VZ6xW2vE2fhzwZM-VrgUCEy0ME0r3SFqkZZpNNEGQrCEipfNccRJ_nFB6uAg&ua=wc-2%2Fjs-2.1.3%2Fwindows10-chrome-108.0.0%2Fbrowser%3Alocalhost%3A3000
    at ft.transportOpen (index.es.js?e35d:1:32288)
    at async Promise.all (:3000/index 1)
    at async ft.init (index.es.js?e35d:1:30881)
    at async V.initialize (index.es.js?e35d:1:52200)
    at async V.start (index.es.js?e35d:1:52102)
    at async C.initialize (index.es.js?eb21:1:25044)
    at async C.init (index.es.js?eb21:1:24873)
    at async a.createClient (index.es.js?380e:1:6082)
    at async a.initialize (index.es.js?380e:1:5952)
    at async a.init (index.es.js?380e:1:4330)
ClientContext.tsx?3ab3:186 Uncaught (in promise) ReferenceError: WalletConnect Client is not initialized.
    at _callee$ (ClientContext.tsx?3ab3:186:11)
    at tryCatch (runtime.js?ecd4:45:16)
    at Generator.invoke [as _invoke] (runtime.js?ecd4:274:1)
    at prototype.<computed> [as next] (runtime.js?ecd4:97:1)
    at asyncGeneratorStep (_async_to_generator.mjs?b18b:3:1)
    at _next (_async_to_generator.mjs?b18b:25:1)
    at eval (_async_to_generator.mjs?b18b:32:1)
    at new Promise (<anonymous>)
    at eval (_async_to_generator.mjs?b18b:21:1)
    at eval (ClientContext.tsx?3ab3:218:71)
    at onClick (Blockchain.tsx?e42d:133:35)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?ac89:4070:1)
    at executeDispatch (react-dom.development.js?ac89:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js?ac89:8275:1)
    at processDispatchQueue (react-dom.development.js?ac89:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js?ac89:8299:1)
    at eval (react-dom.development.js?ac89:8508:1)
    at batchedEventUpdates$1 (react-dom.development.js?ac89:22396:1)
    at batchedEventUpdates (react-dom.development.js?ac89:3745:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js?ac89:8507:1)
    at attemptToDispatchEvent (react-dom.development.js?ac89:6005:1)
    at dispatchEvent (react-dom.development.js?ac89:5924:1)
    at unstable_runWithPriority (scheduler.development.js?bcd2:468:1)
    at runWithPriority$1 (react-dom.development.js?ac89:11276:1)
    at discreteUpdates$1 (react-dom.development.js?ac89:22413:1)
    at discreteUpdates (react-dom.development.js?ac89:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js?ac89:5889:1)```

**Comment by glitch-txs** [comment]
is this because I need to add it in the allowed domain on the cloud? cz when I add localhost there it gets deleted.

**Comment by Utcha** [comment]
Hi @glitch-txs  I have a same problem as you.
I'm also trying to add localhost on the cloud, but the cloud automatically made it "localhost.org" format.
Could you please let me know how you add it?

**Comment by glitch-txs** [comment]
Hey actually the error was related to something else. You don't need to add an URL, the Project ID itself is enough and should work in all cases.

**Comment by Utcha** [comment]
@glitch-txs Thank you so much for your answer, can you tell me where you solved the problem?
I'm having the same problem as you

**Comment by glitch-txs** [comment]
Tbh honest I don't remember, but if you're interested I have a working solution on my repo, still need to work on it though. I'd suggest googling the errors.
